Get auto expand navigation properties from Context.ElementClrType ins…
OData/WebApi pull request #2471
Opened 2021-04-21 14:20 UTC by papillon

### Issues

This pull request fixes issue  #2465.

### Description

 Get auto expand navigation properties from Context.ElementClrType instead of Context.TargetStructuredType

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [x] *Build and test with one-click build and test script passed*

### Additional work necessary

Someone with more in-depth knowledge should check if this proposal is the correct way to do it.

2021-06-09 15:00 UTC, KenitoInc requested changes
Thanks for this PR.
Kindly add test case/cases to validate this fix.

2021-07-14 08:30 UTC, KenitoInc commented
Hey @papillon 
Did you get a chance to look into the pending tests?

2021-07-22 10:02 UTC, papillon commented
I'll see what I can do.

2021-09-07 19:34 UTC, ificator commented
Just noticed this PR - looks like it's attempting to solve the same underlying issue that my new PR (https://github.com/OData/WebApi/pull/2565) is. If this approach (using `ElementClrType` instead of making sure `TargetStructuredType` is populated for operations) is the preferred I can close out my PR.

2021-09-17 01:32 UTC, ificator commented
PR2565 has been merged, so we should see if https://github.com/OData/WebApi/issues/2465 is resolved by it. If so, we can probably abandon this PR.

2021-10-18 20:17 UTC, corranrogue9 commented on src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
> +            else
Please add curly braces to this branch in an attempt to avoid maintainability mistakes

2021-10-18 20:17 UTC, corranrogue9 commented on src/Microsoft.AspNet.OData.Shared/Query/ODataQueryOptions.cs
> +            if (Context.ElementClrType != null)
It would be really good to add a unit test for this

2021-11-04 22:51 UTC, mikepizzo commented
Thanks for the contribution @papillon!

The target issue should be addressed by #2565, which is now merged.  If the issue continues to exist, please re-open.

2021-11-04 22:51 UTC, closed without merging