Fix API Explorer usage with OData.
OData/WebApi pull request #2494
Opened 2021-05-14 13:08 UTC by midgleyc

### Issues

*This pull request fixes issue #1750.*

### Description

*This PR changes ODataInputFormatter and ODataOutputFormatter to override GetSupportedContentTypes to not throw an exception when SupportedMediaTypes is empty.*

This lead to a problem when using Swagger with a controller with both OData and non-OData routes, as seen in https://github.com/OData/WebApi/issues/1177#issuecomment-353738261.

### Checklist (Uncheck if it is not completed)

- [x] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

I don't know what the "one-click build and test script" is, but I ran the newly added unit tests and they pass with this change, and fail without.

2021-06-03 08:03 UTC, midgleyc commented
Fixes #1750.

2021-06-09 14:38 UTC, KenitoInc requested changes

2021-06-09 14:38 UTC, KenitoInc commented on test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/ODataMediaTypeFormattersTests.cs
> +                Assert.Null(exception);
Add another `Assert` for the expected value when calling `GetSupportedContentTypes`

2021-06-09 14:38 UTC, KenitoInc commented on test/UnitTest/Microsoft.Test.AspNet.OData/Formatter/ODataMediaTypeFormattersTests.cs
> +                Assert.Null(exception);
Add another `Assert` for the expected value when calling `GetSupportedContentTypes`

2021-06-10 07:57 UTC, KenitoInc approved these changes

2021-06-16 07:06 UTC, midgleyc commented
I pointed this at `feature/netcore` because reading the descriptions I thought that was the right branch, but it was last updated in 2018. Should I have set it to merge into `master` instead? It rebases cleanly on master.

2021-06-16 07:08 UTC, KenitoInc commented
> I pointed this at `feature/netcore` because reading the descriptions I thought that was the right branch, but it was last updated in 2018. Should I have set it to merge into `master` instead? It rebases cleanly on master.

Point it to master

2021-06-16 07:47 UTC, gathogojr approved these changes
LGTM

2021-06-16 07:49 UTC, gathogojr commented
@midgleyc Can you follow the instructions [here](https://github.com/OData/WebApi/pull/2494/checks?check_run_id=2836870786) to update the baseline? That should fix the failing tests. If you're unable to please let me know so I can clone the branch and update

2021-06-17 07:23 UTC, habbes approved these changes

2021-06-17 09:25 UTC, merged