Fix to ignore Unmapped properties in Delta<T>
OData/WebApi pull request #2544
Opened 2021-08-13 17:04 UTC by Sreejithpin

### Issues

This pull request fixes issue #2532 

### Description

Fix to ignore Unmapped properties in Delta<T>

### Checklist (Uncheck if it is not completed)

- [ ] *Test cases added*
- [ ] *Build and test with one-click build and test script passed*

### Additional work necessary

*If documentation update is needed, please add "Docs Needed" label to the issue and provide details about the required document change in the issue.*

2021-08-13 18:11 UTC, mikepizzo commented on test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/Models/TestDataModels.cs
> +    public class NewCustomerUnmapped
>NewCustomerUnmapped [](http://example.com/codeflow?start=17&length=19)

maybe add a [DataMember] attribute to a property that also has [IgnoreDataMember] and validate that property is serialized if [DataContract] is not applied to the type.

2021-08-13 18:12 UTC, mikepizzo commented on test/UnitTest/Microsoft.AspNet.OData.Test.Shared/TestCommon/Models/TestDataModels.cs
> +        public string Name { get; set; }
Just to cover all of the possibilities, should probably have a property with just the [DataMember] attribute and a property with no attributes.

2021-08-13 18:14 UTC, mikepizzo commented on src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
> +        {
Add a comment to explain the logic here.

2021-08-13 18:15 UTC, mikepizzo commented on src/Microsoft.AspNet.OData.Shared/DeltaOfTStructuralType.cs
> +        private bool IsIgnoredProperty(bool isTypeDataContract, PropertyInfo propertyInfo)
>isTypeDataContract [](http://example.com/codeflow?start=44&length=18)

If the type is marked with [DataContract], but the property is not marked with [DataMember], do we include or ignore it?

2021-08-13 18:17 UTC, mikepizzo requested changes
:clock1:

2021-08-13 20:59 UTC, mikepizzo approved these changes
:shipit:

2021-08-13 21:15 UTC, mikepizzo requested changes
:clock1:

2021-08-13 21:16 UTC, mikepizzo commented on test/UnitTest/Microsoft.AspNet.OData.Test.Shared/DeltaTest.cs
> +            Assert.Equal(2, properties.Count);
>            Assert.Equal(2, properties.Count);   [](http://example.com/codeflow?start=0&length=48)

shouldn't "Id" be returned?

2021-09-23 13:48 UTC, KenitoInc approved these changes
LGTM

2021-10-07 03:14 UTC, mikepizzo approved these changes
:shipit:

2021-10-07 21:27 UTC, merged